spring:
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/cxr_test?characterEncoding=UTF-8
    username: dbuser
    password: Dbuser123!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sungcor.exam.entity
