spring:
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/cxr_test?characterEncoding=UTF-8
    username: dbuser
    password: DBuser123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.0.100
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sungcor.exam.entity

constants:
  url:
    findServer: http://192.168.0.28/store/openapi/v2/resources/query?apikey=e10adc3949ba59abbe56e057f2gg88dd

task:
  data:
    push:
      fixed: 3600000



